package(default_visibility = ["//visibility:public"])

cc_library(
    name = "outcome",
    hdrs = ["outcome.hpp"],
    deps = [
        "//third_party:outcome"
    ]
)

cc_library(
    name = "overload",
    hdrs = [ "overload.hpp" ],
)

cc_library(
    name = "string_manipulation",
    hdrs = [ "string_manipulation.hpp" ],
)
